import { Montserrat } from "next/font/google";
import Header from "./components/Header/Header";

const montserrat = Montserrat(
  { 
    subsets: ["latin"],
    weight: ['100','200','300','400','500','600','700','800','900'] ,
    display: "swap"
  }
);

export const metadata = {
  title: "Azərbaycanın aparıcı xəbər saytı | Report.az",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={montserrat.className}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
